### PR TITLE
ALL: Rename projects

### PR DESCRIPTION
**Pull request by Warepire**
Requires PR #42 

wintaser and wintasee are both bad names (as in making it hard to discern what the purpose is), and annoying as they only differ by one letter at the end making tab-completion annoying.

Proposes new names `client` and `injectee`

### CODE REVIEW

**Comment by YaLTeR** [comment]
Hm, why is the main program called "client"?

**Comment by Warepire** [comment]
It's a proposal.

**Comment by YaLTeR** [comment]
Additional ideas for the project names:
.exe - "hourglass"
.dll - "hooks", "hooklib"

I might have better ideas tomorrow when I'm not falling asleep

**Comment by Warepire** [comment]
The whole project is already called Hourglass, it's not very clear in my opinion if we name the exe source directory `hourglass` as well.
The `hooklib` idea for the dll is pretty good. It's not going to be only hooks though...

**Comment by vadosnaprimer** [comment]
Because the main program is actually a client, as opposed to the usual term "core" in emulators. This word is accurate, descriptive and standard.

**Comment by YaLTeR** [comment]
The word "client" spawns some client-server communication associations in my mind, maybe that's just me.

**Comment by Warepire** [comment]
After consideration and debate I am going to propose `hooks` as suggested by @YaLTeR for the dll part, and `application` for the executable. Which later should be split into `core` and `gui` instead, when the GUI and debugger loop etc can be separated.

Please state opinions.

**Comment by YaLTeR** [comment]
I like the `application`, `core` and `gui` idea very much.

**Comment by Warepire** [comment]
Do the commit look fine?

**Comment by YaLTeR** [comment]
I think so.

**Pull request merged**
