### PR TITLE
3rd party: CRT: Add Minicrt to prepare for new DLL hooking

### PR DESCRIPTION
**Pull request by Warepire**
With a new DLL hooking procedure on the way where the DLL can't depend on DLLs nor code we can't control it needs to link against a different CRT. Minicrt will be of help here.

The source code was initially grabbed from here: http://www.benshoof.org/blog/minicrt/
I updated it to work with VS2015.

NOTE: I want to squash the commits before merge so that unnecessary files that were removed by the commits don't affect the main source tree.

### CODE REVIEW

**Comment by Warepire** [comment]
Actually, this may be problematic license-wise. The base code may be (c) Microsoft.
Closed until this is sorted out.

**Comment by YaLTeR** [comment]
Do you mean that some parts of the code might have been copy pasted from Microsoft's CRT?

**Comment by jroweboy** [comment]
@YaLTeR Warepire means that the original code came from a Microsoft magazine, meaning it probably is copyright Microsoft

http://web.archive.org/web/20070104084126/http://msdn.microsoft.com/msdnmag/issues/01/01/hood/

**Comment by Warepire** [comment]
Well, this CRT isn't going to work, going for another libc instead.

**Pull request closed without merging**
