### PR TITLE
Hooks and Application: Logging and IPC redesign

### PR DESCRIPTION
**Pull request by Warepire**
This PR rewrites the logging and IPC of hourglass to behave in a more "C++" way, and also to work a bit more like `ioctl`, currently the IPC is not 100% implemented as that needs a larger rewrite of the Application side. Evolutions of the Application side might warrant an enhanced implementation on the Hooks side.

This PR also exposes an issue in `VerifyTrustedCaller` that I hack-fixed, this reinforces the need to solve issue #52.

The remaining `OutputDebugStringA` calls can be killed once the Hooks can be injected differently. This will also render many of the IPC commands obsolete.

Please test this code and make sure there are no error messages coming out of `VerifyTrustedCaller`.

---

This change is [Reviewable](https://reviewable.io/reviews/hourglass-resurrection/hourglass-resurrection/54)

### CODE REVIEW

**Comment by Warepire** [comment]
@YaLTeR Do you think you can get a chance to look at this?

**Comment by YaLTeR** [comment]
Reviewed 59 of 59 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_[source/application/logging.cpp, line 66 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwvir-zDNfVX-Urx3R:-KUwvir-zDNfVX-Urx3S:b9runqt) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/application/logging.cpp#L66)):_

> ``` cpp
>         if (debuglogfile)
>         {
>             fwide(debuglogfile, 1);
> ```

Uhhh https://msdn.microsoft.com/ru-ru/library/aa985619.aspx

---

_[source/application/MainMenu.cpp, line 404 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwwE448MLWuJ6xBri0:-KUwwE448MLWuJ6xBri1:b-eeuahb) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/application/MainMenu.cpp#L404)):_

> ``` cpp
>   HelperFuncInsertMenuByID(DebugLogging, i++, Flags | ((localTASflags.log_categories[static_cast<std::underlying_type<LogCategory>::type>(LogCategory::REGISTRY)])?MF_CHECKED:MF_UNCHECKED), ID_INCLUDE_LCF_REGISTRY, "", "Registry", 0);
>   HelperFuncInsertMenuByID(DebugLogging, i++, Flags | ((localTASflags.log_categories[static_cast<std::underlying_type<LogCategory>::type>(LogCategory::THREAD)])?MF_CHECKED:MF_UNCHECKED), ID_INCLUDE_LCF_THREAD, "", "Thread", 0);
>   HelperFuncInsertMenuByID(DebugLogging, i++, Flags | ((localTASflags.log_categories[static_cast<std::underlying_type<LogCategory>::type>(LogCategory::TIMERS)])?MF_CHECKED:MF_UNCHECKED), ID_INCLUDE_LCF_TIMERS, "", "Timers", 0);
> ```

I think it's better to do this like:

``` cpp
#define INSERT(category, name) \
    HelperFuncInsertMenuByID( \
        DebugLogging, \
        i++, \
        Flags \
            | (localTASflags.log_categories[static_cast<std::underlying_type<LogCategory>::type>(LogCategory::category)] \
                ? MF_CHECKED : MF_UNCHECKED), \
        ID_INCLUDE_LCF_ ## category, \
        "", \
        name, \
        0)

INSERT(ANY, "Uncategorized");
INSERT(HOOK, "Hooking");
INSERT(TIME, "Time");
INSERT(DETTIMER, "Det. Timer");
// ...

#undef INSERT
```

---

_[source/application/wintaser.cpp, line 875 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwy9NOQwidpdUAY-WE:-KUwy9NOQwidpdUAY-WF:b9xn59m) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/application/wintaser.cpp#L875)):_

> ``` cpp
> bool dllLoadInfosSent = false;
> 
> void ReceiveDllLoadInfosPointer(LPVOID dll_load_info_pointer)
> ```

`info` or `infos`? The function below also does `infos` in both the function name and the variable name.

---

_[source/application/wintaser.cpp, line 6146 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwyulRLXYItdvmFG70:-KUwyulRLXYItdvmFG71:b1v3uuv) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/application/wintaser.cpp#L6146)):_

> ``` cpp
>                     localTASflags.log_categories[static_cast<std::underlying_type<LogCategory>::type>(LogCategory::TIMERS)] ^= true;
>                     tasFlagsDirty = true;
>                     break;
> ```

Probably better to do with a macro as well.

---

_[source/hooks/ipc.cpp, line 10 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwzoUIcLicO1T-w5O1:-KUwzoUIcLicO1T-w5O2:b-s82fdf) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/hooks/ipc.cpp#L10)):_

> ``` cpp
> {
>     static IPC::CommandFrame cmd_frame;
>     static volatile LONG ipc_lock;
> ```

Is volatile required?

---

_[source/hooks/print.cpp, line 74 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUx-6Y8UBdLmdXRK-hn:-KUx-6Y8UBdLmdXRK-ho:b-ri26n9) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/hooks/print.cpp#L74)):_

> ``` cpp
>         return "[D3D]";
>     case LogCategory::OGL:
>         return "[OpenGL:TODO:Stop wrapping D3D!]";
> ```

Does this TODO belong here though?

---

_[source/hooks/hooks/windowhooks.cpp, line 156 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUx0gOmSmvRMJfYkdNg:-KUx0gOmSmvRMJfYkdNh:b-hpj2qf) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/hooks/hooks/windowhooks.cpp#L156)):_

> ``` cpp
>     {
>         ENTER(X, Y, nWidth, nHeight, dwStyle, dwExStyle);
>         LOG() << "WARNING: Not yet finished";
> ```

I've seen at least two other versions of this message so far ("Warning: Not yet implemented.", "Not yet implemented!")

---

_[source/shared/ipc.h, line 128 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUx1Am3uRmsg0G-Gbgg:-KUx1Am3uRmsg0G-Gbgh:b-ymlx96) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/shared/ipc.h#L128)):_

> ``` objc
> 
> /*
>  * Communication interface for the DLL, all communication is initiated by the DLL .
> ```

Extra space before the dot.

---

_[source/shared/ipc.h, line 212 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUx1OMDrtMrRCprXx5r:-KUx1OMDrtMrRCprXx5s:bb39rab) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/1e564f78174922bd8c9892a2e3029c8608c10233/source/shared/ipc.h#L212)):_

> ``` objc
>         DWORD command_data_size;
>         LPCVOID command_data;
>     };
> ```

Should be `m_`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54)_

**Comment by Warepire** [comment]
Review status: 58 of 59 files reviewed at latest revision, 9 unresolved discussions.

---

_[source/application/logging.cpp, line 66 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwvir-zDNfVX-Urx3R:-KVJinTQ32R6sNpUgcKH:b-3sdhup) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/application/logging.cpp#L66)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> Uhhh https://msdn.microsoft.com/ru-ru/library/aa985619.aspx
> </details>
> Interesting... I still probably want to keep it there, just for documentation.

---

_[source/application/MainMenu.cpp, line 404 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwwE448MLWuJ6xBri0:-KVJj3D2fOgjHhEyt8gL:bw3m0gq) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/application/MainMenu.cpp#L404)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> I think it's better to do this like:
> 
> ``` cpp
> #define INSERT(category, name) \
>     HelperFuncInsertMenuByID( \
>         DebugLogging, \
>         i++, \
>         Flags \
>             | (localTASflags.log_categories[static_cast<std::underlying_type<LogCategory>::type>(LogCategory::category)] \
>                 ? MF_CHECKED : MF_UNCHECKED), \
>         ID_INCLUDE_LCF_ ## category, \
>         "", \
>         name, \
>         0)
> 
> INSERT(ANY, "Uncategorized");
> INSERT(HOOK, "Hooking");
> INSERT(TIME, "Time");
> INSERT(DETTIMER, "Det. Timer");
> // ...
> 
> #undef INSERT
> ```
> 
> </details>
> The application side should have less macros, not more. Also the entire GUI is in need of a major overhaul. Either way I'd say this is out of scope for what this PR does.

---

_[source/application/wintaser.cpp, line 875 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwy9NOQwidpdUAY-WE:-KVJjMtys_agiZ00nA1Z:b-ejqoco) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/application/wintaser.cpp#L875)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> `info` or `infos`? The function below also does `infos` in both the function name and the variable name.
> </details>
> I could fix it, but the entire function and IPC command is destined for the axe.

---

_[source/application/wintaser.cpp, line 6146 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwyulRLXYItdvmFG70:-KVJjd6woJO7HtV-KvQX:bxg4s4n) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/application/wintaser.cpp#L6146)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> Probably better to do with a macro as well.
> </details>
> See my comment regarding the MainMenu.

---

_[source/hooks/ipc.cpp, line 10 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwzoUIcLicO1T-w5O1:-KVJjop1q7H-0g7Levb2:b-xac1ii) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/hooks/ipc.cpp#L10)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> Is volatile required?
> </details>
> The low-level API for atomic operations require volatile. I didn't use the `std::atomic` library here because we're going towards dropping the runtime.

---

_[source/hooks/print.cpp, line 74 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUx-6Y8UBdLmdXRK-hn:-KVJkEb4xhT_wTH5_Imy:b6kd8nf) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/hooks/print.cpp#L74)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> Does this TODO belong here though?
> </details>
> I'd like to keep it, exposing the problem can gather interest from others to fix it.

---

_[source/hooks/hooks/windowhooks.cpp, line 156 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUx0gOmSmvRMJfYkdNg:-KVJkODjDQffZk5ipf-Z:b-vpegyt) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/hooks/hooks/windowhooks.cpp#L156)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> I've seen at least two other versions of this message so far ("Warning: Not yet implemented.", "Not yet implemented!")
> </details>
> Should be unified now.

---

_[source/shared/ipc.h, line 128 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUx1Am3uRmsg0G-Gbgg:-KVJkRW5FoOX5hv4U8NX:b-886gsx) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/shared/ipc.h#L128)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> Extra space before the dot.
> </details>
> Fixed

---

_[source/shared/ipc.h, line 212 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUx1OMDrtMrRCprXx5r:-KVJkStiyKDSlZoJYHlH:b-886gsx) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/shared/ipc.h#L212)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> Should be `m_`
> </details>
> Fixed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54)_

**Comment by YaLTeR** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r2.
Review status: 56 of 59 files reviewed at latest revision, 1 unresolved discussion.

---

_[source/application/MainMenu.cpp, line 404 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwwE448MLWuJ6xBri0:-KVJkna8n_SjYqJIurVG:bb7q6fu) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/application/MainMenu.cpp#L404)):_
<details><summary>

<i>Previously, Warepire wrote…</i></summary>



> The application side should have less macros, not more. Also the entire GUI is in need of a major overhaul. Either way I'd say this is out of scope for what this PR does.
> </details>
> OK; macro uses in places like this are mainly to prevent copypaste errors (and increase readability). (Did starting message with OK work for still setting a "resolved" state?)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-:-KVJlm9uE6__hyH0UslF:bnfp4nl)_

**Comment by Warepire** [comment]
Review status: 56 of 59 files reviewed at latest revision, 1 unresolved discussion.

---

_[source/application/MainMenu.cpp, line 404 at r1](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54#-KUwwE448MLWuJ6xBri0:-KVJm5S74T57uJaQI1QW:bpxl743) ([raw file](https://github.com/hourglass-resurrection/hourglass-resurrection/blob/755dce8da33b96b0359d3a3c2cddd9349ff33402/source/application/MainMenu.cpp#L404)):_
<details><summary>

<i>Previously, YaLTeR (Ivan Molodetskikh) wrote…</i></summary>



> OK; macro uses in places like this are mainly to prevent copypaste errors (and increase readability). (Did starting message with OK work for still setting a "resolved" state?)
> </details>
> Didn't seem so..

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54)_

**Comment by YaLTeR** [comment]
Reviewed 3 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/54)_

**Pull request merged**
