### PR TITLE
DOC: Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Warepire**
Address usage of `auto` and `enum class`

### CODE REVIEW

**Comment by Scepheo** [comment]
Some typos that could be addressed:
Includes: "Windows headers _must be_ included first"
Unsafe functions: "If an advisor says a WinAPI function _is_ unsafe"
Functions, pass-by-pointer: remove period after "globally", spell "i.e." without capital letter.
EXE Special Cases: "in the _executable_"

**Comment by YaLTeR** [comment]
- Add a note for function pointers, style should be something like this: `ReturnType (CallingConvention *Name)(Arguments);`.
- Add a note for this pointer name for hooked functions, it should be named `thisptr`.

**Comment by YaLTeR** [comment]
- The getter / setter definitions should probably be changed to this:

```
[type] Get[VariableNameAsCamelCase]() const;
void Set[VariableNameAsCamelCase]([type] value);
```

**Comment by Warepire** [comment]
There should be some ruling made regarding `using` vs `typedef`.

**Comment by YaLTeR** [comment]
LGTM

**Pull request merged**
