### PR TITLE
BUILD: Automatic builds with AppVeyor

### PR DESCRIPTION
**Pull request by Warepire**
Figured we could use some sort of super-basic buildbot.
I've set up the repo and appveyor to build the master branch on commit, and every pull request made from here-on.

What's left is to re-configure appveyor to use the included build-rules file so that builds can be reconfigured without access to the account (in case I am gone for a week or so and someone wants to make a quick edit)

---

This change is [Reviewable](https://reviewable.io/reviews/hourglass-resurrection/hourglass-resurrection/55)

### CODE REVIEW

**Comment by jroweboy** [comment]
I still can't figure out this review system, so I'm just going to leave my feedback here as a comment.

If you put the appveyor.yml file at the root of the repo I think it automatically detects it and uses it instead. Actually, it might just detect it anywhere in the repo, I'm not too sure on that. I'm just used to seeing it at the base of the repo.

You have the appveyor.yml set to only build on push to master, but also the after build script will check if its a PR. From your comment, it sounds like you don't want the `on: branch: master` part in there.

Also missing is the build environment information. What version of VS is this supposed to be using? Should it build 64bit and 32bit builds?

Looks fine outside of that. One change you might consider making is using the deploy functionality in appveyor to upload releases to other places (since appveyor has very slow download speeds for artifacts). I was thinking it'd be nice to have appveyor build on all PRs (so you can see that the code in the PR compiles and you can grab the artifact from the build to test it with) but then on master branch builds you can upload those to github releases and point people to there instead. To do that, you can add something like the following in the file

``` yaml
deploy:
  - provider: GitHub
    release: hourglass-resurrection-$(appveyor_build_number)
    description: |
      Build Number $(appveyor_build_number)
    auth_token:
      secure: YourSecretHere (get an api token from github and put it through appveyors encrypt data tool and paste it here)
    artifact: /*.zip/
    draft: false # Draft means it won't show up to the public until you click a button on github
    prerelease: false # prerelease builds are tagged with a prerelease icon on the releases page
    on:
      branch: master
      appveyor_repo_tag: false # make appveyor deploy master even if its not tagged
```

I did something similar for citra, and it looks like this on the releases page https://github.com/citra-emu/citra-bleeding-edge/releases

**Comment by Warepire** [comment]
It will not be picked up by default from that location (I am not sure keeping scripts/ in sources/ is a good idea, maybe scripts/ should be at root level), but appveyor can be configured to look for the file elsewhere. I don't like having a ton of files cluttering the root.

It should only build the master branch, and pull requests, the branch config is for the repository only, sure it will break if someone creates a PR against another branch than master, but we don't have any of those.

Leaving the target arch unspecified is intended for now, it's a bug with our solution files, it specifies a target called "Win32", which breaks appveyor if you choose a specific target arch. I need to figure out how to fix this bug, but I didn't consider it relevant to fix in order to introduce this functionality.

The plan is to upload actual release versions to github, the builds provided right now are just interims.

**Comment by Warepire** [comment]
The script has now been enabled as the appveyor config to use. No builds will be triggered without it in it's current location.
I had to make some minor edits to the script so that appveyor would read it correctly.

@jroweboy Please have another look-over on the script, and it's placement. Upon acceptance of this PR, I will file 2 issues, 1 for the broken solution file (specifying a target machine that doesn't exist), and that we need an update to publish releases on GitHub Releases.

**Comment by jroweboy** [comment]
LGTM

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/hourglass-resurrection/hourglass-resurrection/55#-:-KUuJNWeOsgpU49Nj2j1:bb6ywmx)_

**Pull request merged**
