### PR TITLE
Contributing: Replace Windows SDK rules with a target OS rule

### PR DESCRIPTION
**Pull request by Warepire**
The text is obsolete now that we require VS2017 and XP support being dropped.

### CODE REVIEW

**Comment by YaLTeR** [comment]
I suppose we still need a note about Windows 7 (since that's what we're currently targetting?). Pretty sure this can be enforced with some Windows SDK version define (I even saw one set to the XP version somewhere around `wintaser.cpp`, although it should be updated and placed in some shared header).

**Comment by Warepire** [comment]
Hm, you're right. What do you think about something along the lines of: "Current minimum supported OS is Windows 7. Ensure your code can run on this OS."?

**Comment by YaLTeR** [comment]
How about "We're currently targetting Windows 7 and above. Ensure your code can run on Windows 7."?

**Comment by Warepire** [comment]
Yeah, that sounds better. I will update this PR later tonight.

**Comment by Warepire** [comment]
Fell asleep before I got around to updating it yesterday. Took care of it now.

Please squash+merge this one.

**Pull request merged**
